### ISSUE TITLE
curl fails to build with cmake 3.5.1 (maybe due to zlib config?)

### ISSUE THREAD

**Issue by tstack** [hunter-packages/zlib#2]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes|No]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **Yes**

The issue can be reproduced by building the CURL example in hunter itself.

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* [curl-build-fail.log](https://github.com/hunter-packages/zlib/files/3394481/curl-build-fail.log)

I think the real error is this:

```
CMake Error at /home/vagrant/github/hunter/_testing/Hunter/_Base/93db89d/339edb9/1dceb16/Install/lib/cmake/ZLIB/ZLIBConfig.cmake:36 (add_library):
  add_library cannot create ALIAS target "ZLIB::ZLIB" because target
  "ZLIB::zlib" is IMPORTED.
Call Stack (most recent call first):
  CMakeLists.txt:566 (find_package)
```

* I'm building on Linux.
* I'm using system CMake
* CMake version: 3.5.1
* I'm using the default ubuntu/xenial64 vagrant box with cmake installed via apt-get.

* I'm using unmodified toolchain gcc from [Polly](https://github.com/ruslo/polly)

I'm using the next command line on generate step:
```
HUNTER_STATUS_DEBUG=ON TOOLCHAIN=gcc PROJECT_DIR=examples/CURL ./jenkins.py
```

I upgraded cmake to 3.14 installed through pip and CURL built successfully.

---

**Comment by ruslo** [comment]
See https://github.com/hunter-packages/libpng/issues/6

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
